name: Continuous Integration

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100

      - name: Build
        run: dotnet build --configuration Release

      - name: Version and Tag
        id: bump_version
        uses: anothrNick/github-tag-action@1.22.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: master
          WITH_V: true

      - name: Pack
        run: dotnet pack NWN.Core.csproj --configuration Release -p:PackageVersion=${{ steps.bump_version.outputs.tag }} -o output
